trigger:
  branches:
    include:
      - main
  paths:
    include:
      - services/products-api/initiate-checkout/*

pool:
  vmImage: ubuntu-latest

variables:
  - name: servicename
    value: initiate-checkout
  - name: servicepath
    value: products-api/initiate-checkout

jobs:
  - job: Zip_and_Upload
  displayName: 'Zip and Upload'
  steps:
  - template: ${{ variables['System.DefaultWorkingDirectory'] }}/azure-templates/source-version.yml
  - template: ${{ variables['System.DefaultWorkingDirectory'] }}/azure-templates/zip-and-upload.yml
    parameters:
      servicename: $(servicename)
      servicepath: $(servicepath)
      gitcommit:  $(short_hash)