trigger:
  branches:
    include:
      - main
  paths:
    include:
      - services/products-api/initiate-checkout/*

pool:
  vmImage: ubuntu-latest

variables:
  - name: servicename
    value: initiate-checkout
  - name: servicepath
    value: products-api/initiate-checkout

jobs:
  - job: get_short_git_hash
    displayName: 'Get short git hash'
    steps:
      - template: ${{ variables['System.DefaultWorkingDirectory'] }}/azure-templates/source-version.yml

  - job: Zip_and_Upload
    displayName: 'Zip and Upload'
    dependsOn: get_short_git_hash
    variables:
      - name: gitcommit
        value: $[ dependencies.get_short_git_hash.outputs['get_short_hash.short_hash'] ]
      
    steps:
      - template: ${{ variables['System.DefaultWorkingDirectory'] }}/azure-templates/zip-and-upload.yml
        parameters:
          servicename: $(servicename)
          servicepath: $(servicepath)
          gitcommit: $(gitcommit)
