trigger:
  branches:
    include:
      - main
  paths:
    include:
      - services/newsletters/after-signup/*

pool:
  vmImage: ubuntu-latest

variables:
  - name: servicename
    value: newsletters/after-signup

jobs:
  - job: Zip_and_Upload
    displayName: 'Zip and Upload'
    steps:
      - template: ${{ variables['System.DefaultWorkingDirectory'] }}/azure-templates/zip-and-upload.yml
        parameters:
          servicename: $(servicename)
