trigger:
  branches:
    include:
      - main
  paths:
    include:
      - services/support/*

pool:
  vmImage: ubuntu-latest

variables:
  - name: servicename
    value: support

jobs:
  - job: Zip_and_Upload
    displayName: 'Zip and Upload'
    steps:
    - template: ${{variables['System.DefaultWorkingDirectory']}}/azure-templates/zip-and-upload.yml