trigger:
  branches:
    include:
      - main
  paths:
    include:
      - services/support/*

pool:
  vmImage: ubuntu-latest

variables:
  - name: servicename
    value: support

jobs:
  - job: build_test_package
    displayName: 'Build, test, package'
    steps:
      - task: S3Upload@1
        name: upload_cloudformation
        inputs:
          awsCredentials: 'AWS'
          regionName: 'eu-west-1'
          bucketName: 'parisn-bucket'
          createBucket: true
          logRequest: true
          sourceFolder: $(System.DefaultWorkingDirectory)/services/$(servicename)/cloudformation/
          targetFolder: $(servicename)/cloudformation
          logResponse: true
          globExpressions: |
            *.yaml
            **/*.yaml

      - task: CloudFormationCreateOrUpdateStack@1
        inputs:
          awsCredentials: 'AWS'
          regionName: 'eu-west-1'
          stackName: '$(servicename)'
          templateSource: 's3'
          s3BucketName: 'parisn-bucket'
          s3ObjectKey: '$(servicename)/cloudformation/$(servicename).yaml'

      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: '$(Build.BinariesDirectory)'
          includeRootFolder: true
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
          replaceExistingArchive: true

    #   - task: S3Upload@1
    #     displayName: 'Upload all Lambda code zips'
    #     inputs:
    #       awsCredentials: 'AWS'
    #       regionName: 'eu-west-2'
    #       bucketName: 'parisn-bucket'
    #       globExpressions: '**'
    #       createBucket: true
    #       sourceFolder: '$(System.DefaultWorkingDirectory)/test2/cloudformation/'
