trigger:
  branches:
    include:
      - main
  paths:
    include:
      - services/support/*

pool:
  vmImage: ubuntu-latest

variables:
  - name: servicename
    value: support

jobs:
  - job: build_test_package
    displayName: 'Build, test, package'
    steps:
      # Uploads cloud formation
      - task: S3Upload@1
        name: upload_cloudformation
        inputs:
          awsCredentials: 'AWS'
          regionName: 'eu-west-2'
          bucketName: 'parisn-bucket'
          createBucket: true
          logRequest: true
          sourceFolder: $(System.DefaultWorkingDirectory)/services/$(servicename)/cloudformation/
          targetFolder: $(servicename)/cloudformation
          logResponse: true
          globExpressions: |
            *.yaml
            **/*.yaml

      # Archives / zips folder
      - task: ArchiveFiles@2
        displayName: Zip Files
        inputs:
          rootFolderOrFile: '$(System.DefaultWorkingDirectory)/services/$(servicename)'
          includeRootFolder: false
          archiveType: 'zip'
          archiveFile: '$(servicename).zip'
          replaceExistingArchive: true

      # Uploads that zip to S3
      - task: S3Upload@1
        displayName: 'Upload lambda zips'
        condition: suceeded()
        inputs:
          awsCredentials: 'AWS'
          regionName: 'eu-west-2'
          bucketName: 'parisn-bucket'
          globExpressions: '**/*.zip'
          createBucket: true
          logRequest: true
          sourceFolder: '$(System.DefaultWorkingDirectory)/services/$(servicename)'
          targetFolder: '$(servicename)'
        
      # Updates stack using new cloudformation
      - task: CloudFormationCreateOrUpdateStack@1
        displayName: Upload cloud formation
        inputs:
          awsCredentials: 'AWS'
          regionName: 'eu-west-2'
          stackName: '$(servicename)'
          templateSource: 's3'
          s3BucketName: 'parisn-bucket'
          s3ObjectKey: '$(servicename)/cloudformation/$(servicename).yaml'


          ## How do I know where I am in compared to root path?
