trigger:
  branches:
    include:
      - main
  paths:
    include:
      - services/support/*

parameters:

pool:
  vmImage: ubuntu-latest

jobs:
  - job: build_test_package
    displayName: 'Build, test, package'
    steps:
      # # lambda: warning-resolver
      # - template: ${{variables['System.DefaultWorkingDirectory']}}/deployment/pipeline-templates/build-lambda-with-poetry.yml
      #   parameters:
      #     serviceName: $(servicename)
      #     lambdaName: warning_resolver
      #     mainFileName: lambda.py
      #     aws_service_connection: aws.boston.dev # Run the tests in dev
      #     aws_deploy_region: $(Deployment.AWS.Region)

      # BUILD AND TEST COMPLETE - NOW UPLOAD ARTIFACTS
      - task: S3Upload@1
        displayName: 'Upload all Lambda code zips'
        inputs:
          awsCredentials: 'AWS'
          regionName: 'eu-west-2'
          bucketName: 'parisn-bucket'
          globExpressions: '**'

      - task: S3Upload@1
        name: upload_cloudformation
        inputs:
          awsCredentials: 'AWS'
          regionName: 'eu-west-2'
          sourceFolder: '$(System.DefaultWorkingDirectory)/services/$(servicename)/cloudformation/'
          bucketName: 'parisn-bucket'
          globExpressions: |
            *.yaml
            *.json
            **/*.yaml
            **/*.json
